[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.22"
optimizer        = true
optimizer_runs   = 200
via_ir           = true

[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.4.0"
"@openzeppelin-contracts-upgradeable" = "5.4.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
