[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.22"
optimizer        = true
optimizer_runs   = 200
via_ir           = true

# Testing configuration
gas_reports = ["*"]
ffi = false
fs_permissions = [{ access = "read", path = "./"}]

# Fuzz testing
[fuzz]
runs = 1000
max_test_rejects = 65536

# Invariant testing  
[invariant]
runs = 256
depth = 15
fail_on_revert = false
show_metrics = true

# RPC endpoints for Ronin
[rpc_endpoints]
rpc_url = "${RPC_URL}"


[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.4.0"
"@openzeppelin-contracts-upgradeable" = "5.4.0"


