/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KttyWorldCompanions } from "./KttyWorldCompanions";
export * as factories from "./factories";
export { KttyWorldCompanions__factory } from "./factories/KttyWorldCompanions__factory";
